// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5-cX9clpZNdlUH2QfLaDb34Nv-1MoI4',
    appId: '1:273875472910:web:750e73a8eb54552d34625f',
    messagingSenderId: '273875472910',
    projectId: 'beastmode-18f2e',
    authDomain: 'beastmode-18f2e.firebaseapp.com',
    storageBucket: 'beastmode-18f2e.firebasestorage.app',
    measurementId: 'G-ZLKNW5ZGEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCab1JWoPuXPC4rABRMAb4ocPBHu9Jhhj8',
    appId: '1:273875472910:android:958150bf8264ef9734625f',
    messagingSenderId: '273875472910',
    projectId: 'beastmode-18f2e',
    storageBucket: 'beastmode-18f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk5BfbG82JlO8fhhrcca-LxicPVBseFwY',
    appId: '1:273875472910:ios:26315f66ea38df6834625f',
    messagingSenderId: '273875472910',
    projectId: 'beastmode-18f2e',
    storageBucket: 'beastmode-18f2e.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk5BfbG82JlO8fhhrcca-LxicPVBseFwY',
    appId: '1:273875472910:ios:26315f66ea38df6834625f',
    messagingSenderId: '273875472910',
    projectId: 'beastmode-18f2e',
    storageBucket: 'beastmode-18f2e.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP5-cX9clpZNdlUH2QfLaDb34Nv-1MoI4',
    appId: '1:273875472910:web:9d461e8b95331c9434625f',
    messagingSenderId: '273875472910',
    projectId: 'beastmode-18f2e',
    authDomain: 'beastmode-18f2e.firebaseapp.com',
    storageBucket: 'beastmode-18f2e.firebasestorage.app',
    measurementId: 'G-G3VJFCZN5Q',
  );
}